### ISSUE TITLE
Pagination error with bootstrap 5

### ISSUE THREAD

**Issue by scastiello** [DataTables/Dist-DataTables-Bootstrap5#4]
Hi, 

I´m getting the following error with last dev version of datatables and bs5 plugin.

`
jquery.min.js:2 
       Uncaught TypeError: Cannot read properties of undefined (reading 'nodeType')
    at S.fn.init.attr (jquery.min.js:2:65491)
    at $ (jquery.min.js:2:32561)
    at S.fn.init.attr (jquery.min.js:2:65332)
    at o.ext.renderer.pageButton.bootstrap (dataTables.bootstrap5.min.js:1:1953)
    at S.fn.init.fn (jquery.dataTables.min.js:1:34084)
    at jquery.dataTables.min.js:1:47121
    at Function.map (jquery.min.js:2:3536)
    at R (jquery.dataTables.min.js:1:47068)
    at v (jquery.dataTables.min.js:1:23286)
    at B.<anonymous> (jquery.dataTables.min.js:1:54760)
`

The highlight in the paginator is not updated when switch between pages. Show the gif.
![Animation](https://user-images.githubusercontent.com/1845439/195347929-fb6040be-e553-4b5a-a8af-893c3702800b.gif)

Any clue?

**Comment by AllanJard** [comment]
Can you link to a test case showing the issue please?

**Comment by tomsommer** [comment]
Fixed in 1.13.1

**Comment by AllanJard** [comment]
Super - thanks for the update!
