### ISSUE TITLE
Version 1.13.3 is broken

### ISSUE THREAD

**Issue by aeropagz** [DataTables/Dist-DataTables-Bootstrap5#6]
With version 1.13.2 I get this error message:

```
jquery.dataTables.mjs:59 
        
       Uncaught TypeError: Cannot set properties of undefined (setting '$')
    at DataTable (jquery.dataTables.mjs:59:7)
    at Comp.use (datatables.net-vue.esm.js:26522:3)
    at setup (DataTableNetComponent.vue:5:11)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7265:29)
    at setupComponent (runtime-core.esm-bundler.js:7220:11)
    at mountComponent (runtime-core.esm-bundler.js:5542:13)
    at processComponent (runtime-core.esm-bundler.js:5517:17)
    at patch (runtime-core.esm-bundler.js:5119:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5656:21)
```

Changing the version back to 1.12.1 fixes the problem.

**Comment by AllanJard** [comment]
Can you link to a test case showing the issue please. Or set up a repo with instructions on how to reproduce it.

Thanks!

**Comment by aeropagz** [comment]
Sorry was my fault.
I used datatables.net-vue3 libary following [this](https://datatables.net/blog/2022-06-22-vue) tutorial.
But I installed datatables.net-vue3 with version 1.0.1. 
With datatables.net-vue3 2.0.0 bootstrap-datatables is working again. So it was just a version missmatch.
